# Figures and animations shown in the README, rendered from provenance-tracked
# runs into docs/src/assets/ with a PROVENANCE.toml sidecar.
#
#   julia --threads=auto docs/make_readme_assets.jl [COLLECTION_DIR] [--only transition,sweep,kernels,timings]
#
# COLLECTION_DIR defaults to the Geisenheim wind-speed collection under data/
# (generated by scripts/run_pipeline.jl --config configs/geisenheim_wind.toml).
# Assets:
#   transition.png       distributions at a small and a large threshold, survival
#                        function with the scale-free and Pareto-Tsallis fits of
#                        the 2024 recipe (examples/legacy_fit.jl)
#   sweep.gif            the survival function sweeping through the threshold grid
#   kernels.gif          how the search kernels resolve the waiting times of one index
#                        at three thresholds, streaming in packets
#   timings.png          wall time per threshold of every kernel against the naive
#                        reference on a synthetic random walk (minimum of five)
include(joinpath(@__DIR__, "activate.jl"))

using CairoMakie
using Dates: now, UTC
using Optim: Optim, NelderMead, optimize
using Printf: @sprintf
using StableRNGs: StableRNG
using TOML: TOML
using WaitingTimes
using WaitingTimes.Synthetic: random_walk
using WaitingTimes.Provenance: git_state

include(joinpath(dirname(@__DIR__), "examples", "legacy_fit.jl"))

const ASSETS = joinpath(@__DIR__, "src", "assets")
mkpath(ASSETS)
const ONLY = let i = findfirst(==("--only"), ARGS)
    i === nothing ? nothing : split(ARGS[i + 1], ",")
end
wanted(name) = ONLY === nothing || name in ONLY
const THEME = WaitingTimes.figure_theme()
const POSITIONAL = filter(a -> !startswith(a, "--") && (ONLY === nothing || a ∉ ONLY), ARGS)
const COLLECTION = isempty(POSITIONAL) ?
                   let root = joinpath(dirname(@__DIR__), "data")
    rows = list_collections(root)
    i = findfirst(==("geisenheim-wind_speed"), rows.series)
    i === nothing && error("no Geisenheim collection under $root; run the pipeline first")
    rows.dir[i]
end : abspath(POSITIONAL[1])
c = load_collection(COLLECTION)
println("collection ", c.id)
provenance_path = joinpath(ASSETS, "PROVENANCE.toml")
provenance = isfile(provenance_path) && ONLY !== nothing ? TOML.parsefile(provenance_path) :
             Dict{String, Any}("assets" => Dict{String, Any}())
merge!(provenance,
    Dict{String, Any}("collection" => c.id,
        "series" => c.slug, "generated" => string(now(UTC)),
        "git" => git_state(dirname(@__DIR__)),
        "package_version" => string(pkgversion(WaitingTimes))))

# --- transition.png ---------------------------------------------------------------
if wanted("transition")
    # The two regimes of the wind-speed series: δ = 1 km/h (scale-free) and
    # δ = 32.5 km/h (Pareto-Tsallis), survival functions with the fitted models.
    function survival_panel!(ax, d, model, label, color)
        k = Float64.(WaitingTimes.support(d))
        F = WaitingTimes.survival(d)
        keep = F .> 0
        scatter!(
            ax, k[keep], F[keep]; color = :black, strokecolor = :black, markersize = 8,
            label = "Data")
        lines!(ax, k[keep], model.(k[keep]); color = color, linestyle = :dash,
            label = label)
        return ax
    end

    d_small = distribution(c, "1.0")
    d_large = distribution(c, "32.5")
    τs, pmfs, cdfs = Float64.(WaitingTimes.support(d_small)),
    WaitingTimes.probabilities(d_small),
    WaitingTimes.cumulative(d_small)
    sf = fit_scale_free(τs, cdfs)
    τl, pmfl, cdfl = Float64.(WaitingTimes.support(d_large)),
    WaitingTimes.probabilities(d_large),
    WaitingTimes.cumulative(d_large)
    pt = fit_pareto_tsallis(τl, pmfl, cdfl)
    # survival of the fitted models, renormalised on the data support as the fits are
    function sf_survival(k)
        k < sf.x_min ? NaN :
        (WaitingTimes.survival(d_small)[findfirst(>=(sf.x_min), τs)] *
         (k / sf.x_min)^(1 - sf.α))
    end
    function pt_survival(k)
        (1 + k / pt.λ)^(-pt.α) / (1 + τl[1] / pt.λ)^(-pt.α) *
        WaitingTimes.survival(d_large)[1]
    end

    fig = with_theme(THEME) do
        fig = Figure(; size = (1200, 600))
        ax1 = Axis(fig[1, 1]; xscale = log10, yscale = log10,
            xticks = WaitingTimes.decade_ticks(0, 5), yticks = WaitingTimes.decade_ticks(-6, 0),
            xlabel = "Waiting time k [h]", ylabel = "P(τ > k)")
        survival_panel!(ax1, d_small, sf_survival,
            @sprintf("Scale-free, α = %.3f", sf.α), :orangered)
        text!(ax1, 0.03, 0.05; text = "δ = 1 km/h",
            space = :relative, align = (:left, :bottom),
            fontsize = 21)
        ax2 = Axis(fig[1, 2]; xscale = log10, yscale = log10,
            xticks = WaitingTimes.decade_ticks(0, 6), yticks = WaitingTimes.decade_ticks(-6, 0),
            xlabel = "Waiting time k [h]", ylabel = "P(τ > k)")
        survival_panel!(ax2, d_large, pt_survival,
            @sprintf("Pareto-Tsallis, α = %.3f", pt.α), :royalblue3)
        text!(ax2, 0.03, 0.05; text = "δ = 32.5 km/h",
            space = :relative, align = (:left, :bottom),
            fontsize = 21)
        Legend(fig[0, 1], ax1)
        Legend(fig[0, 2], ax2)
        fig
    end
    save(joinpath(ASSETS, "transition.png"), fig; px_per_unit = 2)
    provenance["assets"]["transition.png"] = Dict("deltas" => ["1.0", "32.5"],
        "scale_free" => Dict("alpha" => sf.α, "x_min" => sf.x_min, "ks" => sf.ks),
        "pareto_tsallis" => Dict("alpha" => pt.α, "lambda" => pt.λ, "ks" => pt.ks))
    println("transition.png")
end

# --- sweep.gif ------------------------------------------------------------------
if wanted("sweep")
    # The survival function through the threshold grid, one frame per threshold.
    grid = thresholds(c)
    step = max(1, length(grid) ÷ 100)
    frames = grid[1:step:end]
    fig = with_theme(THEME) do
        fig = Figure(; size = (900, 600))
        ax = Axis(fig[1, 1]; xscale = log10, yscale = log10,
            xticks = WaitingTimes.decade_ticks(0, 6), yticks = WaitingTimes.decade_ticks(-6, 0),
            xlabel = "Waiting time k [h]", ylabel = "P(τ > k)",
            limits = ((0.8, 2e6), (5e-7, 1.5)))
        d0 = distribution(c, frames[1])
        k0 = Float64.(WaitingTimes.support(d0))
        F0 = WaitingTimes.survival(d0)
        keep0 = F0 .> 0
        pts = Observable(Point2f.(k0[keep0], F0[keep0]))
        label = Observable("δ = " * format_threshold(frames[1]) * " km/h")
        scatter!(ax, pts; color = :black, strokecolor = :black, markersize = 8)
        text!(ax, 0.03, 0.05; text = label, space = :relative, align = (:left, :bottom),
            fontsize = 24)
        record(fig, joinpath(ASSETS, "sweep.gif"), frames; framerate = 8) do δ
            d = distribution(c, δ)
            k = Float64.(WaitingTimes.support(d))
            F = WaitingTimes.survival(d)
            keep = F .> 0
            pts[] = Point2f.(k[keep], F[keep])
            label[] = "δ = " * format_threshold(δ) * " km/h"
        end
        fig
    end
    provenance["assets"]["sweep.gif"] = Dict("frames" => length(frames),
        "delta_first" => format_threshold(frames[1]), "delta_last" =>
            format_threshold(frames[end]))
    println("sweep.gif (", length(frames), " frames)")
end

# --- kernels.gif ------------------------------------------------------------------
if wanted("kernels")
    # The waiting times of one index, resolved by every kernel. The naive and guarded
    # scans and the segment tree take one threshold per pass and are shown at the
    # second threshold: the guarded scan tests the suffix maximum and then scans as
    # the naive one; the segment tree climbs to the first subtree whose maximum
    # reaches the target and descends to its leftmost qualifying leaf. The Fenwick
    # sweep answers every threshold in one backward pass: each index queries the
    # smallest recorded index at its target levels and is then recorded under its
    # value; the step line is that query answer for every level. The streaming kernel
    # receives the series in packets and keeps one heap of pending indices per
    # threshold. Every frame is checked against the package kernels.
    q = [6, 7, 4, 5, 7, 3, 6, 5, 9, 7, 10, 8, 11, 9, 6, 10,
        8, 11, 9, 7, 10, 13, 11, 14, 12, 9, 13, 15, 11, 8, 12, 14,
        10, 13, 15, 12, 14, 17, 13, 10, 12, 8, 11, 7, 13, 16, 19, 15]
    N = length(q)
    n0 = 3                             # the index followed
    deltas = [4, 8, 12]                # targets q[3] + δ = 8, 12, 16: resolved at 9, 22, 38
    K = length(deltas)
    k1 = 2                             # threshold of the one-threshold kernels
    packet = 8                         # samples per packet of the streaming kernel
    targets = q[n0] .+ deltas
    passage(j, T) = findfirst(m -> m > j && q[m] >= T, 1:N)
    resolved = [passage(n0, T) for T in targets]
    any(isnothing, resolved) && error("index $n0 is not resolved at every threshold")
    qs = QuantizedSeries(Float64.(q), 0)
    thresholds_q = [threshold(δ, qs) for δ in deltas]
    τF = waiting_times(qs, thresholds_q, FenwickSweep())
    for k in 1:K, j in 1:N

        m = passage(j, q[j] + deltas[k])
        τF[k][j] == (m === nothing ? 0 : m - j) ||
            error("Fenwick sweep disagrees with the forward scan at index $j, δ = $(deltas[k])")
    end
    for alg in (NaiveSearch(), GuardedSearch(), SegmentTreeSearch())
        waiting_times(qs, thresholds_q[k1], alg) == τF[k1] ||
            error("$(nameof(typeof(alg))) disagrees with the Fenwick sweep")
    end
    # frames per second and the hold of each kind of frame in frames
    framerate = 5
    hold = (step = 3, decision = 7, intro = 12, packet = 11, result = 14, summary = 20)

    # an arrow at level y from x0 to x1: a resolved waiting time (labelled with τ when
    # τ > 0) or a pending one; one slot per threshold
    Arrow = @NamedTuple{x0::Int, x1::Int, y::Int, style::Symbol, τ::Int}
    no_arrow = (; x0 = 0, x1 = 0, y = 0, style = :none, τ = 0)
    Frame = @NamedTuple{kernel::String, caption::String, highlight::Vector{Int},
        visited::Vector{Int}, band::UnitRange{Int}, arrived::Int, active::Vector{Int},
        arrows::Vector{Arrow}, staircase::Vector{Point2f}, hold::Int}

    "frames of the animation, each held for `hold` frames of the GIF"
    function kernel_frames()
        frames = Frame[]
        function frame!(kernel, caption, h; highlight = Int[], visited = Int[],
                band = 1:0, arrived = N, active = [k1], arrows = fill(no_arrow, K),
                staircase = Point2f[])
            push!(frames,
                (; kernel, caption, highlight, visited, band, arrived, active,
                    arrows = Arrow.(arrows), staircase, hold = h))
        end
        function one_arrow(x1; style = :resolved)
            a = fill(no_arrow, K)
            a[k1] = (; x0 = n0, x1, y = targets[k1], style,
                τ = style === :resolved ? x1 - n0 : 0)
            return a
        end
        T = targets[k1]
        r = resolved[k1]
        # naive and guarded scans
        name = "Naive and guarded scans (1/4)"
        frame!(
            name, "one threshold per pass: scan the later samples until one reaches the target",
            hold.intro)
        M = WaitingTimes.suffix_maximum(q)
        frame!(name,
            "guarded scan: suffix maximum of $(n0 + 1)–$N is $(M[n0 + 1]) ≥ $T, a passage exists",
            hold.decision; highlight = collect((n0 + 1):N), band = (n0 + 1):N)
        for j in (n0 + 1):r
            hit = q[j] >= T
            frame!(name,
                hit ? "q[$j] = $(q[j]) ≥ $T: τ = $(r - n0)" :
                "q[$j] = $(q[j]) < $T, continue",
                hit ? hold.result : hold.step; highlight = [j],
                visited = collect((n0 + 1):j),
                arrows = one_arrow(j; style = hit ? :resolved : :pending))
        end
        # segment tree, as in first_at_least: climb from the leaf of n0 + 1 to the first
        # right sibling whose maximum reaches the target, then descend, taking the left
        # child when it qualifies and its right sibling otherwise
        name = "Segment tree (2/4)"
        frame!(name, "one threshold per pass: climb over subtree maxima, then descend",
            hold.intro)
        P = nextpow(2, N)
        tree = fill(typemin(Int), 2P)
        tree[P:(P + N - 1)] .= q
        for i in (P - 1):-1:1
            tree[i] = max(tree[2i], tree[2i + 1])
        end
        function cover(i)
            depth = ndigits(i; base = 2) - 1
            width = P >> depth
            lo = (i - (1 << depth)) * width + 1
            return lo:min(lo + width - 1, N)
        end
        function node!(i, verdict; h = hold.decision, arrows = fill(no_arrow, K))
            c = cover(i)
            cmp = tree[i] >= T ? "≥" : "<"
            test = length(c) == 1 ? "leaf $(c[1]): q[$(c[1])] = $(tree[i]) $cmp $T" :
                   "subtree $(c[1])–$(c[end]): maximum $(tree[i]) $cmp $T"
            frame!(name, test * verdict, h; highlight = collect(c), band = c, arrows)
        end
        i = n0 + P
        while tree[i] < T
            node!(i, ", climb")
            while isodd(i)
                i >>= 1
            end
            i += 1
        end
        while i < P
            node!(i, ", descend")
            i <<= 1
            if tree[i] < T
                node!(i, ", take the right sibling")
                i += 1
            end
        end
        i - P + 1 == r || error("segment-tree frames end at $(i - P + 1), not $r")
        node!(i, ": τ = $(r - n0)"; h = hold.result, arrows = one_arrow(r))
        # Fenwick sweep: right to left; index j queries its K target levels, then is
        # recorded under its value
        name = "Fenwick sweep (3/4)"
        frame!(name,
            "one backward pass answers every index at every threshold δ = $(join(deltas, ", "))",
            hold.intro; active = Int[])
        function staircase(j)
            pts = [Point2f(j, 0), Point2f(j, q[j])]
            top = j
            for m in (j + 1):N
                if q[m] > q[top]
                    push!(pts, Point2f(m, q[top]), Point2f(m, q[m]))
                    top = m
                end
            end
            return pts
        end
        explained = false
        for j in N:-1:(n0 + 1)
            arrows = fill(no_arrow, K)
            τs = String[]
            for k in 1:K
                m = τF[k][j] == 0 ? nothing : j + τF[k][j]
                push!(τs, m === nothing ? "–" : string(m - j))
                m === nothing ||
                    (arrows[k] = (;
                        x0 = j, x1 = m, y = q[j] + deltas[k], style = :resolved, τ = 0))
            end
            stair = staircase(j)
            state = (; highlight = [j], visited = collect(j:N), active = Int[], arrows,
                staircase = stair)
            frame!(name,
                "index $j queries levels $(join(q[j] .+ deltas, ", ")): τ = $(join(τs, ", ")); recorded at level $(q[j])",
                hold.step; state...)
            if !explained && length(stair) >= 8
                frame!(name,
                    "step line: for every level, the first recorded index reaching it",
                    hold.intro; state...)
                explained = true
            end
        end
        arrows = [(; x0 = n0, x1 = resolved[k], y = targets[k], style = :resolved,
                      τ = resolved[k] - n0) for k in 1:K]
        frame!(name,
            "index $n0 queries levels $(join(targets, ", ")): τ = $(join(resolved .- n0, ", ")) from the one pass",
            hold.summary; highlight = [n0], visited = collect((n0 + 1):N),
            active = collect(1:K), arrows, staircase = staircase(n0 + 1))
        # streaming: packets arrive left to right; every sample updates one heap per
        # threshold, as OnlineWaitingTimes does
        name = "Streaming (4/4)"
        frame!(name,
            "samples arrive in packets of $packet; one heap of pending indices per threshold",
            hold.intro; arrived = 0, active = collect(1:K))
        states = [StreamingState(qs, thr) for thr in thresholds_q]
        at = zeros(Int, K)                 # resolving index of n0 per threshold
        for lo in 1:packet:N
            hi = min(lo + packet - 1, N)
            before = copy(at)
            count = 0
            for j in lo:hi, k in 1:K

                count += WaitingTimes.update!(states[k], qs.times[j], qs.values[j]) do n, τ
                    n == n0 && (at[k] = n0 + τ)
                end
            end
            arrows = fill(no_arrow, K)
            if hi >= n0
                for k in 1:K
                    arrows[k] = at[k] > 0 ?
                                (; x0 = n0, x1 = at[k], y = targets[k], style = :resolved,
                        τ = at[k] - n0) :
                                (;
                        x0 = n0, x1 = hi, y = targets[k], style = :pending, τ = 0)
                end
            end
            new = findall(k -> before[k] == 0 && at[k] > 0, 1:K)
            waiting = findall(==(0), at)
            caption = "packet $(lo)–$(hi): " *
                      (count == 0 ? "no waiting time resolved" :
                       "$count waiting time$(count == 1 ? "" : "s") resolved") *
                      (lo <= n0 <= hi ? "; index $n0 joins the heap of every threshold" :
                       !isempty(new) ?
                       ", index $n0 at δ = $(join(deltas[new], ", ")) (τ = $(join(at[new] .- n0, ", ")))" :
                       !isempty(waiting) ?
                       "; index $n0 pending at δ = $(join(deltas[waiting], ", "))" :
                       "; $(sum(pending(st) for st in states)) remain pending, right-censored")
            frame!(name, caption, isempty(new) ? hold.packet : hold.result;
                highlight = collect(lo:hi), visited = collect(1:(lo - 1)), band = lo:hi,
                arrived = hi, active = collect(1:K), arrows)
        end
        at .- n0 == [τF[k][n0] for k in 1:K] ||
            error("streaming frames disagree with the Fenwick sweep")
        return frames
    end

    frames = kernel_frames()
    ticks = reduce(vcat, [fill(f, f.hold) for f in frames])
    # Okabe–Ito: one colour per threshold, vermillion for the samples under test, sky
    # blue for visited samples, yellow for the index followed
    threshold_colors = [RGBf(0.0, 0.62, 0.451), RGBf(0.0, 0.447, 0.698),
        RGBf(0.8, 0.475, 0.655)]
    tested = RGBf(0.835, 0.369, 0.0)
    seen = RGBf(0.337, 0.706, 0.914)
    followed = RGBf(0.941, 0.894, 0.259)
    fig = with_theme(THEME) do
        fig = Figure(; size = (1200, 640))
        ax = Axis(fig[3, 1]; xlabel = L"Index $n$", ylabel = L"Value $q_n$",
            xticks = [1; 4:4:N], yticks = 0:5:20, limits = ((0.5, N + 0.5), (0, 21)))
        current = Observable(frames[1])
        band = lift(
            f -> isempty(f.band) ? (0.5, 0.5) : (f.band[1] - 0.5, f.band[end] + 0.5),
            current)
        vspan!(ax, lift(first, band), lift(last, band); color = (tested, 0.08),
            visible = lift(f -> !isempty(f.band), current))
        for k in 1:K
            c = threshold_colors[k]
            hlines!(ax, [targets[k]]; linestyle = :dash, linewidth = 1.5,
                color = lift(f -> RGBAf(c.r, c.g, c.b, k in f.active ? 1.0 : 0.25), current))
            text!(ax, 0.7, targets[k]; text = L"q_3 + %$(deltas[k])", color = c,
                align = (:left, :bottom), offset = (0, 2), fontsize = 20)
        end
        lines!(ax,
            lift(f -> isempty(f.staircase) ? [Point2f(NaN, NaN)] : f.staircase, current);
            color = :grey25, linewidth = 2.5)
        scatter!(ax, Point2f.(1:N, q); strokewidth = 0, markersize = 10,
            color = lift(
                f -> [j <= f.arrived ? RGBAf(0, 0, 0, 1) : RGBAf(0, 0, 0, 0.18)
                      for j in 1:N],
                current))
        scatter!(ax, lift(f -> Point2f[(j, q[j]) for j in f.visited], current);
            color = (seen, 0.5), strokecolor = seen, markersize = 18, label = "Visited")
        scatter!(ax, lift(f -> Point2f[(j, q[j]) for j in f.highlight], current);
            color = tested, strokecolor = tested, markersize = 20, label = "Under test")
        for k in 1:K
            c = threshold_colors[k]
            nan = Point2f(NaN, NaN)
            function segment(f, style)
                f.arrows[k].style === style ?
                [Point2f(f.arrows[k].x0, f.arrows[k].y),
                    Point2f(f.arrows[k].x1, f.arrows[k].y)] : [nan, nan]
            end
            lines!(ax, lift(f -> segment(f, :resolved), current); color = c, linewidth = 3)
            # the wait elapsed so far, a translucent bar over the target line
            lines!(ax, lift(f -> segment(f, :pending), current); color = (c, 0.4),
                linewidth = 7)
            scatter!(ax,
                lift(
                    f -> f.arrows[k].style === :resolved ?
                         [Point2f(f.arrows[k].x1 - 0.3, f.arrows[k].y)] : [nan],
                    current);
                marker = :rtriangle, color = c, strokewidth = 0, markersize = 16)
            text!(ax,
                lift(
                    f -> f.arrows[k].τ > 0 ?
                         [Point2f((f.arrows[k].x0 + f.arrows[k].x1) / 2, f.arrows[k].y)] :
                         [nan],
                    current);
                text = lift(f -> [L"\tau = %$(f.arrows[k].τ)"], current), color = c,
                align = (:center, :bottom), offset = (0, 3), fontsize = 20)
        end
        scatter!(ax, [Point2f(n0, q[n0])]; color = followed, strokecolor = :black,
            markersize = 18, label = L"Index followed, $n = %$n0$")
        Label(fig[2, 1],
            lift(f -> rich(rich(f.kernel; font = :bold), "   ", f.caption), current);
            halign = :left, tellwidth = false, fontsize = 22)
        Legend(fig[1, 1], ax)
        rowgap!(fig.layout, 8)
        record(fig, joinpath(ASSETS, "kernels.gif"), ticks; framerate) do f
            current[] = f
        end
        fig
    end
    provenance["assets"]["kernels.gif"] = Dict("series" => q, "index" => n0,
        "deltas" => deltas, "delta_one_pass" => deltas[k1], "packet" => packet,
        "frames" => length(frames), "framerate" => framerate,
        "duration_s" => length(ticks) / framerate)
    println("kernels.gif (", length(frames), " frames, ", length(ticks) / framerate, " s)")
end

# --- timings.png -----------------------------------------------------------------
if wanted("timings")
    # Wall time per threshold of every kernel on a synthetic random walk, against
    # the naive reference kernel, for three thresholds.
    rng = StableRNG(20260927)
    sizes = [10_000, 100_000, 1_000_000]
    deltas = [0.5, 5.0, 50.0]
    kernels = [
        ("Naive (reference)", NaiveSearch(), :black), ("Guarded", GuardedSearch(), :grey40),
        ("Segment tree", SegmentTreeSearch(), :orangered),
        ("Fenwick sweep", FenwickSweep(), :royalblue3), (
            "Streaming", StreamingSearch(), :seagreen)]
    timings = Dict{String, Vector{Float64}}(name => Float64[] for (name, _, _) in kernels)
    labels = String[]
    for Nsize in sizes
        s = QuantizedSeries(random_walk(rng, Nsize), 2)
        for δ in deltas
            thr = threshold(δ, s)
            push!(labels,
                @sprintf("%s\nδ = %g",
                    Nsize == 1_000_000 ? "10⁶" :
                    Nsize == 100_000 ? "10⁵" : "10⁴", δ))
            for (name, alg, _) in kernels
                ws = WaitingTimes.workspace(alg, s)
                waiting_times(s, thr, alg; workspace = ws)          # warm-up
                t = minimum(@elapsed(waiting_times(s, thr, alg; workspace = ws))
                for _ in 1:5)
                push!(timings[name], t)
            end
        end
    end
    fig = with_theme(THEME) do
        fig = Figure(; size = (1200, 600))
        ax = Axis(fig[1, 1]; yscale = log10, xlabel = "Series length and threshold",
            ylabel = "Wall time per threshold [s]", xticks = (1:length(labels), labels),
            xticklabelsize = 18, yticks = WaitingTimes.decade_ticks(-4, 1))
        x = 1:length(labels)
        for (name, _, color) in kernels
            scatterlines!(
                ax, x, timings[name]; color = color, strokecolor = color, label = name,
                markersize = 12)
        end
        Legend(fig[0, 1], ax)
        fig
    end
    save(joinpath(ASSETS, "timings.png"), fig; px_per_unit = 2)
    provenance["assets"]["timings.png"] = Dict("sizes" => sizes, "deltas" => deltas,
        "threads" => Threads.nthreads(), "seconds" => timings)
    println("timings.png")
end

open(provenance_path, "w") do io
    TOML.print(io, provenance; sorted = true)
end
println("assets written to ", ASSETS)
