# Figures and animations shown in the README, rendered from provenance-tracked
# runs into docs/src/assets/ with a PROVENANCE.toml sidecar.
#
#   julia --threads=auto docs/make_readme_assets.jl [COLLECTION_DIR] [--only transition,sweep,kernels,timings]
#
# COLLECTION_DIR defaults to the Geisenheim wind-speed collection under data/
# (generated by scripts/run_pipeline.jl --config configs/geisenheim_wind.toml).
# Assets:
#   transition.png       distributions at a small and a large threshold, survival
#                        function with the scale-free and Pareto-Tsallis fits of
#                        the 2024 recipe (examples/legacy_fit.jl)
#   sweep.gif            the survival function sweeping through the threshold grid
#   kernels.gif          how the five search kernels resolve the same waiting time
#   timings.png          wall time per threshold of every kernel against the naive
#                        reference on a synthetic random walk (minimum of five)
include(joinpath(@__DIR__, "activate.jl"))

using CairoMakie
using Dates: now, UTC
using Optim: Optim, NelderMead, optimize
using Printf: @sprintf
using StableRNGs: StableRNG
using TOML: TOML
using WaitingTimes
using WaitingTimes.Synthetic: random_walk
using WaitingTimes.Provenance: git_state

include(joinpath(dirname(@__DIR__), "examples", "legacy_fit.jl"))

const ASSETS = joinpath(@__DIR__, "src", "assets")
mkpath(ASSETS)
const ONLY = let i = findfirst(==("--only"), ARGS)
    i === nothing ? nothing : split(ARGS[i + 1], ",")
end
wanted(name) = ONLY === nothing || name in ONLY
const THEME = WaitingTimes.figure_theme()
const POSITIONAL = filter(a -> !startswith(a, "--") && (ONLY === nothing || a ∉ ONLY), ARGS)
const COLLECTION = isempty(POSITIONAL) ?
                   let root = joinpath(dirname(@__DIR__), "data")
    rows = list_collections(root)
    i = findfirst(==("geisenheim-wind_speed"), rows.series)
    i === nothing && error("no Geisenheim collection under $root; run the pipeline first")
    rows.dir[i]
end : abspath(POSITIONAL[1])
c = load_collection(COLLECTION)
println("collection ", c.id)
provenance_path = joinpath(ASSETS, "PROVENANCE.toml")
provenance = isfile(provenance_path) && ONLY !== nothing ? TOML.parsefile(provenance_path) :
             Dict{String, Any}("assets" => Dict{String, Any}())
merge!(provenance,
    Dict{String, Any}("collection" => c.id,
        "series" => c.slug, "generated" => string(now(UTC)),
        "git" => git_state(dirname(@__DIR__)),
        "package_version" => string(pkgversion(WaitingTimes))))

# --- transition.png ---------------------------------------------------------------
if wanted("transition")
    # The two regimes of the wind-speed series: δ = 1 km/h (scale-free) and
    # δ = 32.5 km/h (Pareto-Tsallis), survival functions with the fitted models.
    function survival_panel!(ax, d, model, label, color)
        k = Float64.(WaitingTimes.support(d))
        F = WaitingTimes.survival(d)
        keep = F .> 0
        scatter!(
            ax, k[keep], F[keep]; color = :black, strokecolor = :black, markersize = 8,
            label = "Data")
        lines!(ax, k[keep], model.(k[keep]); color = color, linestyle = :dash,
            label = label)
        return ax
    end

    d_small = distribution(c, "1.0")
    d_large = distribution(c, "32.5")
    τs, pmfs, cdfs = Float64.(WaitingTimes.support(d_small)),
    WaitingTimes.probabilities(d_small),
    WaitingTimes.cumulative(d_small)
    sf = fit_scale_free(τs, cdfs)
    τl, pmfl, cdfl = Float64.(WaitingTimes.support(d_large)),
    WaitingTimes.probabilities(d_large),
    WaitingTimes.cumulative(d_large)
    pt = fit_pareto_tsallis(τl, pmfl, cdfl)
    # survival of the fitted models, renormalised on the data support as the fits are
    function sf_survival(k)
        k < sf.x_min ? NaN :
        (WaitingTimes.survival(d_small)[findfirst(>=(sf.x_min), τs)] *
         (k / sf.x_min)^(1 - sf.α))
    end
    function pt_survival(k)
        (1 + k / pt.λ)^(-pt.α) / (1 + τl[1] / pt.λ)^(-pt.α) *
        WaitingTimes.survival(d_large)[1]
    end

    fig = with_theme(THEME) do
        fig = Figure(; size = (1200, 600))
        ax1 = Axis(fig[1, 1]; xscale = log10, yscale = log10,
            xticks = WaitingTimes.decade_ticks(0, 5), yticks = WaitingTimes.decade_ticks(-6, 0),
            xlabel = "Waiting time k [h]", ylabel = "P(τ > k)")
        survival_panel!(ax1, d_small, sf_survival,
            @sprintf("Scale-free, α = %.3f", sf.α), :orangered)
        text!(ax1, 0.03, 0.05; text = "δ = 1 km/h",
            space = :relative, align = (:left, :bottom),
            fontsize = 21)
        ax2 = Axis(fig[1, 2]; xscale = log10, yscale = log10,
            xticks = WaitingTimes.decade_ticks(0, 6), yticks = WaitingTimes.decade_ticks(-6, 0),
            xlabel = "Waiting time k [h]", ylabel = "P(τ > k)")
        survival_panel!(ax2, d_large, pt_survival,
            @sprintf("Pareto-Tsallis, α = %.3f", pt.α), :royalblue3)
        text!(ax2, 0.03, 0.05; text = "δ = 32.5 km/h",
            space = :relative, align = (:left, :bottom),
            fontsize = 21)
        Legend(fig[0, 1], ax1)
        Legend(fig[0, 2], ax2)
        fig
    end
    save(joinpath(ASSETS, "transition.png"), fig; px_per_unit = 2)
    provenance["assets"]["transition.png"] = Dict("deltas" => ["1.0", "32.5"],
        "scale_free" => Dict("alpha" => sf.α, "x_min" => sf.x_min, "ks" => sf.ks),
        "pareto_tsallis" => Dict("alpha" => pt.α, "lambda" => pt.λ, "ks" => pt.ks))
    println("transition.png")
end

# --- sweep.gif ------------------------------------------------------------------
if wanted("sweep")
    # The survival function through the threshold grid, one frame per threshold.
    grid = thresholds(c)
    step = max(1, length(grid) ÷ 100)
    frames = grid[1:step:end]
    fig = with_theme(THEME) do
        fig = Figure(; size = (900, 600))
        ax = Axis(fig[1, 1]; xscale = log10, yscale = log10,
            xticks = WaitingTimes.decade_ticks(0, 6), yticks = WaitingTimes.decade_ticks(-6, 0),
            xlabel = "Waiting time k [h]", ylabel = "P(τ > k)",
            limits = ((0.8, 2e6), (5e-7, 1.5)))
        d0 = distribution(c, frames[1])
        k0 = Float64.(WaitingTimes.support(d0))
        F0 = WaitingTimes.survival(d0)
        keep0 = F0 .> 0
        pts = Observable(Point2f.(k0[keep0], F0[keep0]))
        label = Observable("δ = " * format_threshold(frames[1]) * " km/h")
        scatter!(ax, pts; color = :black, strokecolor = :black, markersize = 8)
        text!(ax, 0.03, 0.05; text = label, space = :relative, align = (:left, :bottom),
            fontsize = 24)
        record(fig, joinpath(ASSETS, "sweep.gif"), frames; framerate = 8) do δ
            d = distribution(c, δ)
            k = Float64.(WaitingTimes.support(d))
            F = WaitingTimes.survival(d)
            keep = F .> 0
            pts[] = Point2f.(k[keep], F[keep])
            label[] = "δ = " * format_threshold(δ) * " km/h"
        end
        fig
    end
    provenance["assets"]["sweep.gif"] = Dict("frames" => length(frames),
        "delta_first" => format_threshold(frames[1]), "delta_last" =>
            format_threshold(frames[end]))
    println("sweep.gif (", length(frames), " frames)")
end

# --- kernels.gif ------------------------------------------------------------------
if wanted("kernels")
    # One index of a small series, resolved by every kernel: the naive scan visits
    # every later sample until the target; the guarded scan first tests the suffix
    # maximum; the segment tree climbs to the first subtree whose maximum reaches the
    # target and descends to its leftmost qualifying leaf; the Fenwick sweep walks
    # the series backwards and asks, at the index, for the smallest index seen with a
    # value at least the target; the streaming kernel keeps the index pending until
    # the resolving sample arrives.
    q = [3, 5, 2, 6, 4, 4, 7, 5, 9, 6, 8, 10, 7, 9, 11, 8]
    N = length(q)
    n0 = 3                     # the index followed
    d0 = 5                     # threshold: target = q[3] + 5 = 7, resolved at index 7
    target = q[n0] + d0
    resolved_at = findfirst(j -> j > n0 && q[j] >= target, 1:N)

    "frames of (kernel name, highlighted indices, visited indices, caption)"
    function kernel_frames()
        frames = Tuple{String, Vector{Int}, Vector{Int}, String}[]
        # naive
        visited = Int[]
        for j in (n0 + 1):resolved_at
            push!(visited, j)
            push!(frames,
                ("Naive scan", [j], copy(visited),
                    q[j] >= target ? "q[$j] = $(q[j]) ≥ $target: τ = $(j - n0)" :
                    "q[$j] = $(q[j]) < $target, continue"))
        end
        # guarded
        M = WaitingTimes.suffix_maximum(q)
        push!(frames,
            ("Guarded scan", collect((n0 + 1):N), Int[],
                "suffix maximum $(M[n0 + 1]) ≥ $target: a passage exists"))
        visited = Int[]
        for j in (n0 + 1):resolved_at
            push!(visited, j)
            push!(frames,
                ("Guarded scan", [j], copy(visited),
                    q[j] >= target ? "q[$j] = $(q[j]) ≥ $target: τ = $(j - n0)" :
                    "q[$j] = $(q[j]) < $target, continue"))
        end
        # segment tree: climb over blocks of 1, 2, 4 ... from n0 + 1
        P = nextpow(2, N)
        tree = fill(typemin(Int), 2P)
        for i in 1:N
            tree[P + i - 1] = q[i]
        end
        for i in (P - 1):-1:1
            tree[i] = max(tree[2i], tree[2i + 1])
        end
        lo = n0 + 1
        i = lo + P - 1
        push!(frames, ("Segment tree", [lo], Int[],
            "leaf $lo: $(q[lo]) < $target, climb"))
        while true
            while isodd(i)
                i >>= 1
            end
            i += 1
            span = i
            depth = floor(Int, log2(i))
            width = P >> depth
            first = (i - (1 << depth)) * width + 1
            block = collect(first:min(first + width - 1, N))
            if tree[i] >= target
                push!(frames,
                    ("Segment tree", block, Int[],
                        "subtree $(first)–$(first + width - 1): maximum $(tree[i]) ≥ $target, descend"))
                while i < P
                    i <<= 1
                    tree[i] < target && (i += 1)
                    depth = floor(Int, log2(i))
                    width = P >> depth
                    first = (i - (1 << depth)) * width + 1
                    push!(frames,
                        ("Segment tree", collect(first:min(first + width - 1, N)), Int[],
                            "subtree $(first)–$(first + width - 1): maximum $(tree[i]) $(tree[i] >= target ? "≥" : "<") $target"))
                end
                j = i - P + 1
                push!(frames, ("Segment tree", [j], Int[], "leaf $j: τ = $(j - n0)"))
                break
            else
                push!(frames,
                    ("Segment tree", block, Int[],
                        "subtree $(first)–$(first + width - 1): maximum $(tree[i]) < $target, climb"))
            end
        end
        # Fenwick sweep: right to left, the smallest index seen with value ≥ target
        seen = Int[]
        for j in N:-1:n0
            if j > n0
                push!(seen, j)
                push!(frames, ("Fenwick sweep", [j], copy(seen),
                    "index $j recorded under value $(q[j])"))
            else
                push!(frames,
                    ("Fenwick sweep", [j], copy(seen),
                        "index $j asks: smallest index with value ≥ $target is $resolved_at: τ = $(resolved_at - n0)"))
            end
        end
        # streaming: samples arrive left to right; the index waits in the heap
        for j in 1:resolved_at
            push!(frames,
                ("Streaming", [j], collect(n0:min(j, resolved_at - 1)),
                    j < n0 ? "sample $j arrives" :
                    j == n0 ? "sample $j arrives and joins the heap with target $target" :
                    q[j] >= target ?
                    "sample $j = $(q[j]) ≥ $target resolves index $n0: τ = $(j - n0)" :
                    "sample $j = $(q[j]) < $target; index $n0 stays pending"))
        end
        return frames
    end

    frames = kernel_frames()
    fig = with_theme(THEME) do
        fig = Figure(; size = (1200, 600))
        ax = Axis(fig[1, 1]; xlabel = L"Index $n$", ylabel = L"Value $q_n$",
            xticks = 1:N, limits = ((0.5, N + 0.5), (0, 13)))
        hlines!(ax, [target]; color = :orangered, linestyle = :dash,
            label = L"Target $q_3 + \delta = %$target$")
        hlines!(ax, [q[n0]]; color = :grey, linestyle = :dot, label = L"$q_3 = %$(q[n0])$")
        visited_pts = Observable(Point2f[])
        highlight_pts = Observable(Point2f[])
        scatter!(
            ax, Point2f.(1:N, q); color = :black, strokecolor = :black, markersize = 12)
        scatter!(ax, visited_pts; color = (:royalblue3, 0.45), strokecolor = :royalblue3,
            markersize = 20)
        scatter!(ax, highlight_pts; color = :orangered,
            strokecolor = :orangered, markersize = 24)
        scatter!(
            ax, [Point2f(n0, q[n0])]; color = :gold, strokecolor = :black, markersize = 20,
            label = "Index followed, n = $n0")
        title = Observable(frames[1][1])
        caption = Observable(frames[1][4])
        text!(ax, 0.02, 0.97; text = title, space = :relative, align = (:left, :top),
            fontsize = 24, font = :bold)
        text!(ax, 0.02, 0.89; text = caption, space = :relative, align = (:left, :top),
            fontsize = 21)
        Legend(fig[0, 1], ax)
        record(fig, joinpath(ASSETS, "kernels.gif"), frames; framerate = 2) do (
            name, hi, vis, cap)
            title[] = name
            caption[] = cap
            visited_pts[] = Point2f[(j, q[j]) for j in vis]
            highlight_pts[] = Point2f[(j, q[j]) for j in hi]
        end
        fig
    end
    provenance["assets"]["kernels.gif"] = Dict("series" => q, "index" => n0, "delta" => d0,
        "frames" => length(frames))
    println("kernels.gif (", length(frames), " frames)")
end

# --- timings.png -----------------------------------------------------------------
if wanted("timings")
    # Wall time per threshold of every kernel on a synthetic random walk, against
    # the naive reference kernel, for three thresholds.
    rng = StableRNG(20260927)
    sizes = [10_000, 100_000, 1_000_000]
    deltas = [0.5, 5.0, 50.0]
    kernels = [
        ("Naive (reference)", NaiveSearch(), :black), ("Guarded", GuardedSearch(), :grey40),
        ("Segment tree", SegmentTreeSearch(), :orangered),
        ("Fenwick sweep", FenwickSweep(), :royalblue3), (
            "Streaming", StreamingSearch(), :seagreen)]
    timings = Dict{String, Vector{Float64}}(name => Float64[] for (name, _, _) in kernels)
    labels = String[]
    for Nsize in sizes
        s = QuantizedSeries(random_walk(rng, Nsize), 2)
        for δ in deltas
            thr = threshold(δ, s)
            push!(labels,
                @sprintf("%s\nδ = %g",
                    Nsize == 1_000_000 ? "10⁶" :
                    Nsize == 100_000 ? "10⁵" : "10⁴", δ))
            for (name, alg, _) in kernels
                ws = WaitingTimes.workspace(alg, s)
                waiting_times(s, thr, alg; workspace = ws)          # warm-up
                t = minimum(@elapsed(waiting_times(s, thr, alg; workspace = ws))
                for _ in 1:5)
                push!(timings[name], t)
            end
        end
    end
    fig = with_theme(THEME) do
        fig = Figure(; size = (1200, 600))
        ax = Axis(fig[1, 1]; yscale = log10, xlabel = "Series length and threshold",
            ylabel = "Wall time per threshold [s]", xticks = (1:length(labels), labels),
            xticklabelsize = 18, yticks = WaitingTimes.decade_ticks(-4, 1))
        x = 1:length(labels)
        for (name, _, color) in kernels
            scatterlines!(
                ax, x, timings[name]; color = color, strokecolor = color, label = name,
                markersize = 12)
        end
        Legend(fig[0, 1], ax)
        fig
    end
    save(joinpath(ASSETS, "timings.png"), fig; px_per_unit = 2)
    provenance["assets"]["timings.png"] = Dict("sizes" => sizes, "deltas" => deltas,
        "threads" => Threads.nthreads(), "seconds" => timings)
    println("timings.png")
end

open(provenance_path, "w") do io
    TOML.print(io, provenance; sorted = true)
end
println("assets written to ", ASSETS)
